# -*- encoding: utf-8 -*-
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'melisa/version'

Gem::Specification.new do |gem|
  gem.name = "melisa"
  gem.summary = "Melisa is a Rubyesque wrapper for the Marisa Trie C library"
  gem.description = "Melisa installs the marisa-trie C library and makes a ruby class Melisa::Trie that is an easy interface."
  gem.homepage = "http://github.com/wordtreefoundation/melisa"
  gem.authors = ['Duane Johnson']
  gem.email = ['duane.johnson@gmail.com']
  gem.licenses = ["MIT"]

  gem.files = %w[melisa.gemspec README.md]
  gem.files += Dir.glob("lib/**/*.rb")
  gem.files += Dir.glob("spec/**/*")

  # Configure marisa external C library
  gem.files += Dir.glob("ext/*.h")
  gem.files += Dir.glob("ext/*.cxx")
  gem.files += Dir.glob("ext/marisa-*/**/*")
  gem.platform = Gem::Platform::RUBY
  gem.extensions = Dir['ext/**/extconf.rb']

  # Binary files generated by marisa are configured to go to melisa/bin
  gem.bindir = 'bin'
  gem.executables += ['melisa']

  gem.test_files = Dir.glob("spec/**/*")
  gem.require_paths = ["lib", "ext"]
  gem.version = Melisa::VERSION
  gem.required_ruby_version = '>= 1.9.0'

  gem.add_development_dependency "rake", "~> 13.0"
  gem.add_development_dependency "rspec", "~> 3.1"
end
